import {
  AdminConfig,
  Deployment,
  Location,
  Organisation,
  Question,
  QuestionBinding,
  ServiceTicket,
  SyncBatch,
  TelemetryEvent,
  Unit,
} from '../types';

export const INITIAL_CONFIG: AdminConfig = {
  pilot_bin_count: 8,
  pilot_start_date: '2026-09-20',
  pilot_end_date: '2026-11-20',
  heartbeat_interval_min: 15,
  storage_retention_days: 60,
  storage_fill_warning_pct: 85,
  clock_drift_tolerance_sec: 120,
  min_sensor_gap_ms: 300,
  lcd_display_mode: 'session',
  target_syncs_per_merchant_day: 3,
  silent_threshold_hours: 48,
  scan_duration_sec: 8,
  max_unsent_batches: 5,
  sync_on_foreground: true,
  unbound_session_max_hours: 72,
  merchant_reset_confirm_prompt: true,
  default_manual_confidence: 'Medium',
  include_low_confidence_in_reports: true,
  max_notifications_per_day: 4,
  quiet_hours_start: '22:00',
  quiet_hours_end: '07:00',
  merchants_see_leaderboard: true,
  vote_rate_drop_alert_pct: 40,
};

export const INITIAL_ORGANISATIONS: Organisation[] = [
  {
    id: 'org-01',
    name: 'Shree Balaji Paan & Refreshments',
    contact_phone: '+91 98290 11420',
    contact_person: 'Ramesh Tiwari',
    type: 'shop',
    onboarding_date: '2026-09-20',
    status: 'active',
  },
  {
    id: 'org-02',
    name: 'Jai Hind Corner & Cafe',
    contact_phone: '+91 94141 55210',
    contact_person: 'Suresh Sharma',
    type: 'cafe',
    onboarding_date: '2026-09-21',
    status: 'active',
  },
  {
    id: 'org-03',
    name: 'Kota Chai Point',
    contact_phone: '+91 97845 22901',
    contact_person: 'Vikram Chauhan',
    type: 'shop',
    onboarding_date: '2026-09-22',
    status: 'active',
  },
  {
    id: 'org-04',
    name: 'Royal Paan Palace',
    contact_phone: '+91 98291 77334',
    contact_person: 'Deepak Verma',
    type: 'shop',
    onboarding_date: '2026-09-23',
    status: 'active',
  },
];

export const INITIAL_LOCATIONS: Location[] = [
  {
    id: 'loc-01',
    org_id: 'org-01',
    name: 'Rangbari Main Gate Shop',
    address: 'Plot 14, Main Road, Rangbari, Kota, Rajasthan 324005',
    coordinates: { lat: 25.1384, lng: 75.8362 },
    area_locality_tag: 'Rangbari',
    descriptor: 'Outside main counter, right next to customer checkout point',
  },
  {
    id: 'loc-02',
    org_id: 'org-02',
    name: 'Talwandi Circle Outlet',
    address: 'Near Commerce College Circle, Talwandi, Kota 324005',
    coordinates: { lat: 25.1528, lng: 75.8427 },
    area_locality_tag: 'Talwandi',
    descriptor: 'Front sidewalk column under awning, beside high student footfall corridor',
  },
  {
    id: 'loc-03',
    org_id: 'org-03',
    name: 'Vigyan Nagar Coaching Strip',
    address: 'Road No. 2, Vigyan Nagar, Kota 324005',
    coordinates: { lat: 25.1611, lng: 75.8541 },
    area_locality_tag: 'Vigyan Nagar',
    descriptor: 'Outside tea stall gate, left of cigarette display case',
  },
  {
    id: 'loc-04',
    org_id: 'org-04',
    name: 'Gumanpura Market Stall',
    address: 'Shop 88, Multi-Purpose School Road, Gumanpura, Kota 324007',
    coordinates: { lat: 25.1762, lng: 75.8398 },
    area_locality_tag: 'Gumanpura',
    descriptor: 'Center pillar between paan preparation slab and street entrance',
  },
];

export const INITIAL_DEPLOYMENTS: Deployment[] = [
  {
    id: 'dep-01',
    unit_serial: 'CC-BIN-01',
    location_id: 'loc-01',
    installed_date: '2026-09-20',
    installed_by: 'FA-Manoj-01',
    notes: 'Mounted on heavy steel bracket with security wire at 1.1m height.',
    active: true,
  },
  {
    id: 'dep-02',
    unit_serial: 'CC-BIN-02',
    location_id: 'loc-02',
    installed_date: '2026-09-21',
    installed_by: 'FA-Manoj-01',
    notes: 'Plugged to shop mains adaptor; battery backup tested OK.',
    active: true,
  },
  {
    id: 'dep-03',
    unit_serial: 'CC-BIN-03',
    location_id: 'loc-03',
    installed_date: '2026-09-22',
    installed_by: 'FA-Pooja-02',
    notes: 'Running on internal 18650 Li-ion pack, merchant charges overnight.',
    active: true,
  },
  {
    id: 'dep-04',
    unit_serial: 'CC-BIN-04',
    location_id: 'loc-04',
    installed_date: '2026-09-23',
    installed_by: 'FA-Pooja-02',
    notes: 'Wall mounted outside tea counter.',
    active: true,
  },
  {
    id: 'dep-05',
    unit_serial: 'CC-BIN-05',
    location_id: 'loc-01',
    installed_date: '2026-09-25',
    installed_by: 'FA-Manoj-01',
    notes: 'Pilot testing 3-hole prototype in high volume zone.',
    active: true,
  },
];

export const INITIAL_UNITS: Unit[] = [
  {
    serial: 'CC-BIN-01',
    product_type: 'survey_bin',
    hardware_revision: 'REV 1.2',
    firmware_version: 'v1.0.4',
    per_device_secret: 'sec_cc_bin_01_a891',
    assembly_date: '2026-09-15',
    current_status: 'Healthy',
    battery_level: 92,
    power_source: 'mains',
    clock_drift_ms: 42,
    last_sync_time: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    last_power_on: '2026-10-01T07:00:00Z',
    last_vote_time: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    current_session_id: 4,
    storage_fill_pct: 18,
    counts: { A: 412, B: 288 },
    location_id: 'loc-01',
    org_id: 'org-01',
  },
  {
    serial: 'CC-BIN-02',
    product_type: 'survey_bin',
    hardware_revision: 'REV 1.2',
    firmware_version: 'v1.0.4',
    per_device_secret: 'sec_cc_bin_02_b712',
    assembly_date: '2026-09-15',
    current_status: 'Healthy',
    battery_level: 86,
    power_source: 'mains',
    clock_drift_ms: -18,
    last_sync_time: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    last_power_on: '2026-10-01T07:30:00Z',
    last_vote_time: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    current_session_id: 3,
    storage_fill_pct: 24,
    counts: { A: 198, B: 341 },
    location_id: 'loc-02',
    org_id: 'org-02',
  },
  {
    serial: 'CC-BIN-03',
    product_type: 'survey_bin',
    hardware_revision: 'REV 1.1',
    firmware_version: 'v1.0.3',
    per_device_secret: 'sec_cc_bin_03_c990',
    assembly_date: '2026-09-16',
    current_status: 'Quiet',
    battery_level: 54,
    power_source: 'battery',
    clock_drift_ms: 110,
    last_sync_time: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
    last_power_on: '2026-09-30T10:15:00Z',
    last_vote_time: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    current_session_id: 5,
    storage_fill_pct: 35,
    counts: { A: 85, B: 112 },
    location_id: 'loc-03',
    org_id: 'org-03',
  },
  {
    serial: 'CC-BIN-04',
    product_type: 'survey_bin',
    hardware_revision: 'REV 1.1',
    firmware_version: 'v1.0.2',
    per_device_secret: 'sec_cc_bin_04_d221',
    assembly_date: '2026-09-16',
    current_status: 'Silent',
    battery_level: 19,
    power_source: 'battery',
    clock_drift_ms: 412,
    last_sync_time: new Date(Date.now() - 52 * 3600 * 1000).toISOString(),
    last_power_on: '2026-09-28T08:00:00Z',
    last_vote_time: new Date(Date.now() - 50 * 3600 * 1000).toISOString(),
    current_session_id: 2,
    storage_fill_pct: 42,
    counts: { A: 320, B: 290 },
    location_id: 'loc-04',
    org_id: 'org-04',
  },
  {
    serial: 'CC-BIN-05',
    product_type: 'survey_bin',
    hardware_revision: 'REV 1.2',
    firmware_version: 'v1.0.4',
    per_device_secret: 'sec_cc_bin_05_e445',
    assembly_date: '2026-09-17',
    current_status: 'Faulty',
    battery_level: 78,
    power_source: 'mains',
    clock_drift_ms: 12,
    last_sync_time: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    last_power_on: '2026-10-02T06:00:00Z',
    last_vote_time: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    current_session_id: 6,
    storage_fill_pct: 61,
    counts: { A: 512, B: 12, C: 44 },
    location_id: 'loc-01',
    org_id: 'org-01',
  },
  {
    serial: 'CC-BIN-06',
    product_type: 'survey_bin',
    hardware_revision: 'REV 1.2',
    firmware_version: 'v1.0.4',
    per_device_secret: 'sec_cc_bin_06_f901',
    assembly_date: '2026-10-01',
    current_status: 'Unassigned',
    battery_level: 100,
    power_source: 'battery',
    clock_drift_ms: 0,
    last_sync_time: '2026-10-01T12:00:00Z',
    last_power_on: '2026-10-01T12:00:00Z',
    last_vote_time: '',
    current_session_id: 1,
    storage_fill_pct: 2,
    counts: { A: 0, B: 0 },
  },
  {
    serial: 'CC-BIN-07',
    product_type: 'survey_bin',
    hardware_revision: 'REV 1.2',
    firmware_version: 'v1.0.4',
    per_device_secret: 'sec_cc_bin_07_g112',
    assembly_date: '2026-09-18',
    current_status: 'Healthy',
    battery_level: 88,
    power_source: 'mains',
    clock_drift_ms: 15,
    last_sync_time: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    last_power_on: '2026-10-02T08:00:00Z',
    last_vote_time: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    current_session_id: 7,
    storage_fill_pct: 9,
    counts: { A: 28, B: 20 },
    location_id: 'loc-02',
    org_id: 'org-02',
  },
  {
    serial: 'CC-BIN-08',
    product_type: 'survey_bin',
    hardware_revision: 'REV 1.0',
    firmware_version: 'v1.0.0',
    per_device_secret: 'sec_cc_bin_08_h334',
    assembly_date: '2026-09-10',
    current_status: 'Retired',
    battery_level: 0,
    power_source: 'battery',
    clock_drift_ms: 999,
    last_sync_time: '2026-09-22T18:00:00Z',
    last_power_on: '2026-09-22T08:00:00Z',
    last_vote_time: '2026-09-22T17:40:00Z',
    current_session_id: 2,
    storage_fill_pct: 88,
    counts: { A: 94, B: 81 },
  },
];

export const INITIAL_QUESTIONS: Question[] = [
  {
    id: 'q-01',
    text: 'क्या कोटा में रात 10 बजे के बाद लाइब्रेरी खुलनी चाहिए? / Should student libraries stay open past 10 PM in Kota?',
    language: 'Hindi',
    category: 'Education',
    options: [
      { hole_id: 'A', label: 'हाँ / YES' },
      { hole_id: 'B', label: 'नहीं / NO' },
    ],
    active_start: '2026-09-20',
    active_end: '2026-10-10',
    author: 'Admin Team (Mukesh)',
    created_at: '2026-09-19T10:00:00Z',
  },
  {
    id: 'q-02',
    text: 'सार्वजनिक स्थान पर कचरा फेंकने पर ₹500 का तत्काल जुर्माना होना चाहिए? / Should there be a ₹500 spot fine for littering in public?',
    language: 'Hindi',
    category: 'Civic',
    options: [
      { hole_id: 'A', label: 'सहमत / AGREE' },
      { hole_id: 'B', label: 'असहमत / DISAGREE' },
    ],
    active_start: '2026-09-21',
    active_end: '2026-10-15',
    author: 'Admin Team (Mukesh)',
    created_at: '2026-09-20T14:30:00Z',
  },
  {
    id: 'q-03',
    text: 'JEE / NEET तैयारी में ऑनलाइन vs ऑफलाइन टेस्ट सीरीज: कौन अधिक मददगार है? / JEE prep: Online or Offline Mock Tests?',
    language: 'Hindi',
    category: 'Youth',
    options: [
      { hole_id: 'A', label: 'ऑनलाइन / ONLINE' },
      { hole_id: 'B', label: 'ऑफलाइन / OFFLINE' },
    ],
    active_start: '2026-09-25',
    active_end: '2026-10-25',
    author: 'Research Team',
    created_at: '2026-09-24T09:15:00Z',
  },
  {
    id: 'q-04',
    text: 'कोटा में ई-रिक्शा का किराया मीटर द्वारा तय किया जाना चाहिए? / Should Kota E-Rickshaws operate on metered fares?',
    language: 'Hindi',
    category: 'Civic',
    options: [
      { hole_id: 'A', label: 'हाँ / YES' },
      { hole_id: 'B', label: 'नहीं / NO' },
    ],
    active_start: '2026-09-28',
    active_end: '2026-10-20',
    author: 'Civic Pilot Desk',
    created_at: '2026-09-27T16:00:00Z',
  },
];

export const INITIAL_BINDINGS: QuestionBinding[] = [
  {
    id: 'bind-01',
    unit_serial: 'CC-BIN-01',
    deployment_id: 'dep-01',
    question_id: 'q-01',
    session_id: 4,
    start_time: '2026-10-01T07:00:00Z',
    source: 'merchant_confirmed',
    confidence: 'Medium-high',
    recorded_by: 'Admin / Ramesh (Prompt)',
    recorded_at: '2026-10-01T07:15:00Z',
    votes_count: 700,
    notes: 'Merchant confirmed question card change at morning reset.',
  },
  {
    id: 'bind-02',
    unit_serial: 'CC-BIN-02',
    deployment_id: 'dep-02',
    question_id: 'q-02',
    session_id: 3,
    start_time: '2026-10-01T07:30:00Z',
    source: 'manual_backend',
    confidence: 'Medium',
    recorded_by: 'Staff (FA-Manoj)',
    recorded_at: '2026-10-01T08:00:00Z',
    votes_count: 539,
  },
  {
    id: 'bind-03',
    unit_serial: 'CC-BIN-03',
    deployment_id: 'dep-03',
    question_id: 'q-03',
    session_id: 5,
    start_time: '2026-09-30T10:15:00Z',
    source: 'merchant_confirmed',
    confidence: 'Medium-high',
    recorded_by: 'Staff (FA-Pooja)',
    recorded_at: '2026-09-30T11:00:00Z',
    votes_count: 197,
  },
  {
    id: 'bind-04',
    unit_serial: 'CC-BIN-04',
    deployment_id: 'dep-04',
    question_id: 'q-01',
    session_id: 2,
    start_time: '2026-09-28T08:00:00Z',
    source: 'manual_backend',
    confidence: 'Medium',
    recorded_by: 'Admin Team',
    recorded_at: '2026-09-28T08:30:00Z',
    votes_count: 610,
  },
  // Unbound session in the queue (Section 10 & 16)
  {
    id: 'bind-unbound-01',
    unit_serial: 'CC-BIN-07',
    deployment_id: 'dep-02',
    question_id: undefined,
    session_id: 7,
    start_time: '2026-10-02T14:14:00Z',
    source: 'unbound',
    confidence: 'None',
    recorded_by: 'System (BLE Reset Event)',
    recorded_at: '2026-10-02T14:14:00Z',
    votes_count: 48,
    notes: 'New session opened at 2:14 PM today after reset switch pressed. 48 votes so far, no question attached.',
  },
];

export const INITIAL_SYNC_BATCHES: SyncBatch[] = [
  {
    id: 'sb-1092',
    unit_serial: 'CC-BIN-01',
    courier_phone: '+91 98290 11420',
    courier_name: 'Ramesh Tiwari (Merchant)',
    courier_role: 'merchant',
    start_time: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    end_time: new Date(Date.now() - 13 * 60 * 1000).toISOString(),
    connection_type: 'BLE',
    event_count: 64,
    sequence_range: [1820, 1884],
    result: 'success',
    uploaded_to_server: true,
  },
  {
    id: 'sb-1091',
    unit_serial: 'CC-BIN-02',
    courier_phone: '+91 94141 55210',
    courier_name: 'Suresh Sharma (Merchant)',
    courier_role: 'merchant',
    start_time: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    end_time: new Date(Date.now() - 44 * 60 * 1000).toISOString(),
    connection_type: 'BLE',
    event_count: 32,
    sequence_range: [940, 972],
    result: 'success',
    uploaded_to_server: true,
  },
  {
    id: 'sb-1090',
    unit_serial: 'CC-BIN-05',
    courier_phone: '+91 99999 10001',
    courier_name: 'Manoj Kumar (Field Agent)',
    courier_role: 'field_agent',
    start_time: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    end_time: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    connection_type: 'BLE',
    event_count: 110,
    sequence_range: [2100, 2210],
    result: 'success',
    uploaded_to_server: true,
  },
  {
    id: 'sb-1089',
    unit_serial: 'CC-BIN-03',
    courier_phone: '+91 97845 22901',
    courier_name: 'Vikram Chauhan (Merchant)',
    courier_role: 'merchant',
    start_time: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
    end_time: new Date(Date.now() - 18 * 3600 * 1000).toISOString(),
    connection_type: 'BLE',
    event_count: 85,
    sequence_range: [410, 495],
    result: 'success',
    uploaded_to_server: true,
  },
];

export const INITIAL_TICKETS: ServiceTicket[] = [
  {
    id: 'tkt-01',
    unit_serial: 'CC-BIN-05',
    location_name: 'Rangbari Main Gate Shop',
    merchant_name: 'Ramesh Tiwari',
    merchant_phone: '+91 98290 11420',
    issue_type: 'counter_wrong',
    notes: 'Sensor Hole B is blocked by chewing gum foil wrapper. Reading frozen.',
    status: 'in_progress',
    created_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },
  {
    id: 'tkt-02',
    unit_serial: 'CC-BIN-04',
    location_name: 'Gumanpura Market Stall',
    merchant_name: 'Deepak Verma',
    merchant_phone: '+91 98291 77334',
    issue_type: 'bin_damaged',
    notes: 'Power wire disconnected during pavement cleaning. Running on backup battery.',
    status: 'open',
    created_at: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },
];

// Sample footfall hourly distribution (Section 11)
export const SAMPLE_HOURLY_FOOTFALL = [
  { hour: '06:00', votesA: 4, votesB: 2, total: 6 },
  { hour: '07:00', votesA: 18, votesB: 12, total: 30 },
  { hour: '08:00', votesA: 42, votesB: 31, total: 73 },
  { hour: '09:00', votesA: 68, votesB: 49, total: 117 },
  { hour: '10:00', votesA: 55, votesB: 38, total: 93 },
  { hour: '11:00', votesA: 34, votesB: 22, total: 56 },
  { hour: '12:00', votesA: 40, votesB: 28, total: 68 },
  { hour: '13:00', votesA: 48, votesB: 35, total: 83 },
  { hour: '14:00', votesA: 30, votesB: 18, total: 48 },
  { hour: '15:00', votesA: 26, votesB: 19, total: 45 },
  { hour: '16:00', votesA: 52, votesB: 36, total: 88 },
  { hour: '17:00', votesA: 88, votesB: 64, total: 152 },
  { hour: '18:00', votesA: 110, votesB: 78, total: 188 },
  { hour: '19:00', votesA: 95, votesB: 70, total: 165 },
  { hour: '20:00', votesA: 72, votesB: 50, total: 122 },
  { hour: '21:00', votesA: 44, votesB: 32, total: 76 },
  { hour: '22:00', votesA: 15, votesB: 8, total: 23 },
];
